version: "3.8"

services:
  nuxt-app:
    image: nuxt_app_prod:latest
    build:
      context: ..
      dockerfile: devbox/Dockerfile.prod
    container_name: nuxt_prod
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./env/.env.production
    depends_on:
      database-prod:
        condition: service_healthy
    networks:
      - app_network

  database-prod:
    image: postgres:15
    container_name: postgres_prod
    restart: always
    environment:
      - POSTGRES_DB=mydb_prod
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - pg_data_prod:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb_prod"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx_prod
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nuxt-app
    networks:
      - app_network

volumes:
  pg_data_prod:
    driver: local

networks:
  app_network:
    driver: bridge
