FROM node:22.14.0

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

RUN pnpm --version

COPY app/package.json app/pnpm-lock.yaml ./

RUN pnpm install

COPY ./app /app

ENV NODE_ENV=development

EXPOSE 3000

CMD ["pnpm", "dev"]
