FROM node:22.14.0

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

RUN pnpm --version

COPY app/package.json app/pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY app .

ENV NODE_ENV=production

RUN pnpm build

EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]
