FROM node:22.14.0

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY app/package.json app/pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY ./app /app

EXPOSE 3000

CMD ["pnpm", "dev"]
