version: "3.8"

services:
  nuxt-app:
    image: nuxt_app_dev
    build:
      context: ..
      dockerfile: devbox/Dockerfile.dev
    container_name: nuxt_dev
    ports:
      - "3200:3000"
    volumes:
      - ../app:/app
      - /app/node_modules
    env_file:
      - ./env/.env.development
    depends_on:
      - database
    networks:
      - app_network

  database:
    image: postgres:15
    container_name: postgres_dev
    environment:
      - POSTGRES_DB=mydb_dev
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
