name: Build & Push Docker Image

on:
  workflow_run:
    workflows: ["E2E UI Tests"]
    types: ["completed"]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build a single image
        run: |
          docker build \
            -f devbox/Dockerfile.prod \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/nuxt_app:latest \
            .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/nuxt_app:latest
