name: Deploy Production

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build, test and deploy integration"]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Deploy to Production VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/nuxt_app:latest
            cd /home/github-ci/tiny-struct/devbox
            ./run.sh stop prod
            ./run.sh start prod 
            docker image prune -f
            docker logout
