name: Deploy Integration

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Integration on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/github-ci/devbox
            ./run.sh stop int
            ./run.sh stop prod
            ./run.sh start int
            ./run.sh start prod
