name: E2E UI Tests

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🔑 Connect to Staging VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Définition du chemin staging
            STAGING_DIR="/home/github-ci/staging"

            # Vérifier si le dossier existe, sinon le créer
            if [ ! -d "$STAGING_DIR" ]; then
                echo "📁 Creating staging directory..."
                mkdir -p "$STAGING_DIR"
            fi

            cd "$STAGING_DIR" 

            # Vérifier si le repo est présent, sinon cloner
            if [ ! -d ".git" ]; then
                echo "🔄 Cloning repository in staging directory..."
                git clone https://github.com/cedric-pouilleux/tiny-struct.git .
            else
                echo "🔄 Resetting local changes and pulling latest changes..."
                git reset --hard origin/main  # 🔥 Force l'alignement avec main
                git fetch --all  # 🔄 Récupère les dernières modifications
                git pull origin main --force  # 🔄 Force la mise à jour sans conflit
            fi
            docker compose --env-file /home/github-ci/devbox/env/.env.integration --profile staging build nuxt-app-staging
            docker compose --env-file /home/github-ci/devbox/env/.env.integration --profile staging up -d --build

  e2e-tests:
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: success()
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🛠️ Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: 🌍 Install Playwright browsers
        run: pnpm playwright install --with-deps

      - name: 🕵️ Run Playwright tests on staging
        run: pnpm test:e2e
        env:
          BASE_URL: "https://localhost:4100"

  trigger-build:
    runs-on: ubuntu-latest
    needs: e2e-tests
    if: success()
    steps:
      - name: ✅ Trigger build.yml
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "Build & Push Docker Image"
