name: E2E UI Tests

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🔑 Connect to Staging VM & Run Tests
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/github-ci/tiny-struct/

            git fetch --all
            git reset --hard origin/main
            git pull origin main --ff-only

            cd /home/github-ci/tiny-struct/devbox
            docker compose --env-file ./env/.env.integration --profile staging up -d --build

  e2e-tests:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: 🔑 Connect to Staging VM & Run Playwright tests
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/github-ci/tiny-struct/devbox

            echo "🚀 Starting Playwright E2E tests on VM..."

            docker compose up --abort-on-container-exit e2e-tests

            echo "✅ Tests completed. Cleaning up..."
            docker compose down
